internal/encoding/tag: use proto3 defaults if proto3
proto3 legacy struct field tags are improperly parsed as proto2,
resulting in fd.L1.EditionFeatures.IsFieldPresence set to true when it
should have been false. This causes coderFieldInfo.isPointer to be true
for said fields. When the encode process (particularly
MessageInfo.sizePointerSlow) sees isPointer=true for the field, it
attempts to interpret the field as a pointer, which results in a "fatal
error: checkptr: misaligned pointer conversion" runtime error if the
field address happens to not be pointer-aligned. This only happens if
building with -race/-asan/-msan as they enable checkptr.

To avoid this issue, parse from proto3 edition defaults if the proto3
key is found in the struct field tag.

Change-Id: Id81ab38fe7efd437d0748a485653d27b1acc3afb
Reviewed-on: https://go-review.googlesource.com/c/protobuf/+/716360
TryBot-Bypass: Michael Stapelberg <stapelberg@google.com>
Auto-Submit: Nicolas Hillegeer <aktau@google.com>
Reviewed-by: Nicolas Hillegeer <aktau@google.com>
LUCI-TryBot-Result: Go LUCI <golang-scoped@luci-project-accounts.iam.gserviceaccount.com>
Run-TryBot: Damien Neil <dneil@google.com>
Reviewed-by: Damien Neil <dneil@google.com>
Reviewed-by: Chressie Himpel <chressie@google.com>
Reviewed-by: Michael Stapelberg <stapelberg@google.com>